language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - npm run lint
  - npm run test
# Node 6 doesn't run prepare after install:
before_script: "npm run build"
# Send test coverage data to Coveralls:
after_script: "npm run coveralls"
